# Generated by Django 5.1.15 on 2026-02-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(choices=[('legit', 'Legitimate'), ('phishing', 'Phishing'), ('review', 'Needs Review')], max_length=10)),
                ('confidence_score', models.FloatField()),
                ('reason', models.TextField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('crawled_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crawler.crawledurl')),
            ],
        ),
    ]
