# Generated by Django 6.0.3 on 2026-03-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_urlanalysis_crawled_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlanalysis',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
