# Generated by Django 5.1.15 on 2026-02-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_rename_discovered_at_crawledurl_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledurl',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='crawledurl',
            name='website_url',
            field=models.URLField(),
        ),
    ]
