# Generated by Django 5.1.15 on 2026-02-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='crawler', max_length=100)),
                ('is_analyzed', models.BooleanField(default=False)),
            ],
        ),
    ]
