# Generated by Django 5.1.15 on 2026-02-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawledurl',
            old_name='discovered_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='crawledurl',
            name='is_analyzed',
        ),
        migrations.RemoveField(
            model_name='crawledurl',
            name='source',
        ),
        migrations.RemoveField(
            model_name='crawledurl',
            name='url',
        ),
        migrations.AddField(
            model_name='crawledurl',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('analyzed', 'Analyzed'), ('blocked', 'Blocked')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='crawledurl',
            name='website_url',
            field=models.URLField(default='https://example.com', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crawledurl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
