# Generated by Django 6.0.2 on 2026-02-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_alter_crawledurl_status_alter_crawledurl_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledurl',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processed', 'Processed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='crawledurl',
            name='website_url',
            field=models.URLField(unique=True),
        ),
    ]
