# Generated by Django 6.0.3 on 2026-03-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_crawledurl_status_alter_crawledurl_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledurl',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processed', 'Processed'), ('pending', 'Pending'), ('blocked', 'Blocked'), ('legitimate', 'Legitimate'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='new', max_length=20),
        ),
    ]
