# Generated by Django 5.1.15 on 2026-02-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationrequest',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='remarks',
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='requested_document',
            field=models.CharField(choices=[('pan', 'PAN Card'), ('passport', 'Passport')], default='pan', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
