# Generated by Django 6.0.2 on 2026-02-11 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_crawledurl_status_alter_crawledurl_website_url'),
        ('decision', '0002_rename_requested_at_verificationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='final_decision',
            field=models.CharField(choices=[('legitimate', 'Legitimate'), ('phishing', 'Phishing'), ('review', 'Needs Review')], default='review', max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='crawled_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='crawler.crawledurl'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='requested_document',
            field=models.TextField(blank=True, null=True),
        ),
    ]
