# Generated by Django 5.1.15 on 2026-02-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationlog',
            old_name='sent_to',
            new_name='user_email',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='crawled_url',
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
