# Generated by Django 5.1.15 on 2026-02-10 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('crawler', '0002_rename_discovered_at_crawledurl_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlanalysis',
            name='crawled_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='crawler.crawledurl'),
        ),
        migrations.AlterField(
            model_name='urlanalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
