# Generated by Django 6.0.2 on 2026-02-11 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_urlanalysis_crawled_url_alter_urlanalysis_id'),
        ('crawler', '0004_alter_crawledurl_status_alter_crawledurl_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlanalysis',
            name='crawled_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crawler.crawledurl'),
        ),
        migrations.AlterField(
            model_name='urlanalysis',
            name='prediction',
            field=models.CharField(max_length=20),
        ),
    ]
